spring:
  application:
    name: spring-parallel-request-process
  aop:
    proxy-target-class: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"